<?php
$weapons = array (
  "Amygdalan Arm",
  "Beast Claw",
  "Beast Cutter",
  "Beasthunter Saif",
  "Blade of Mercy",
  "Bloodletter",
  "Boom Hammer",
  "Burial Blade",
  "Cannon",
  "Chikage",
  "Church Cannon",
  "Church Pick",
  "Double-barreled Shotgun",
  "Evelyn",
  "Fist of Gratia",
  "Flamesprayer",
  "Gatling Gun",
  "Holy Moonlight Sword",
  "Hunter Axe",
  "Hunter Blunderbuss",
  "Hunter Pistol",
  "Hunter's Torch",
  "Kirkhammer",
  "Kos Parasite",
  "Loch Shield",
  "Logarius' Wheel",
  "Ludwig's Holy Blade",
  "Ludwig's Rifle",
  "Piercing Rifle",
  "Rakuyo",
  "Reiterpallasch",
  "Repeating Pistol",
  "Rifle Spear",
  "Rosmarinus",
  "Saw Cleaver",
  "Saw Spear",
  "Simon's Bowblade",
  "Stake Driver",
  "Threaded Cane",
  "Tonitrus",
  "Torch",
  "Whirligig Saw"
);


sort($weapons);
?>